export { default as Home } from './Home'
export { default as People } from './People'
export { default as Search } from './Search'
export { default as Favorite } from './Favorite'
export { default as Profile } from './Profile'
